export { default as About } from './About'
export { default as Account } from './Account'
export { default as Contact } from './Contact'
export { default as Home } from './Home'
export { default as Login } from './Login'